import type { Metadata } from 'next'
import './globals.css'
import { Providers } from '@/components/Provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head></head>

      <body className="bg-slate-800 font-Poppins">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
